name: CI Workflow

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Output personal information
        run: |
          echo "Кривулец Владислав Викторович"
          echo "M3112"
          echo "Benti261"

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest geometric_lib/tests/test_circle.py
          pytest geometric_lib/tests/test_square.py

      - name: Check code formatting with black
        id: black_check
        run: |
          pip install black
          black --check . || echo "Code is not formatted correctly."

      - name: Format code with black
        if: steps.black_check.outcome != 'success'
        run: |
          pip install black
          black .
