name: CI

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - master
      - release
      - develop
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FULL_NAME: "Салов Никита Ильич"
      GROUP_NUMBER: "M3114"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display user information
        run: |
          echo "ФИО: $FULL_NAME"
          echo "Номер группы: $GROUP_NUMBER"
          echo "Ник на GitHub: ${{ github.actor }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 .
      
      - name: Set PYTHONPATH
      run: |
      export PYTHONPATH=$PYTHONPATH:$(pwd)

      - name: Run tests
        run: |
          pytest