name: Python Tests Workflow

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FULL_NAME: "Смирнова Александра Дмитриевна"
      GROUP_NUMBER: "M3116"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print information
        run: |
          echo "ФИО: ${{ env.FULL_NAME }}"
          echo "Номер группы: ${{ env.GROUP_NUMBER }}"
          echo "Ник на Github: ${{ github.actor }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p "test_*.py"

      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 
