name: Tests Workflow

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FULL_NAME: "Lukashenko kirill Denisovich"
      GROUP_NUMBER: "M3117"
      NICKNAME_GITHUB: "JanartYho"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print information
        run: |
          echo "Full Name: ${{ env.FULL_NAME }}"
          echo "Group Name ${{ env.GROUP_NUMBER }}"
          echo "Nickname Github: ${{ github.actor }}"
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Run unit_tests
        run: |
          python -m unittest
      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 --ignore=F401 .
