name: Test

on:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FULL_NAME: "Зимин Михаил Михайлович"  
      GROUP_NUMBER: "M3110"  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display Information
        run: |
          echo "ФИО: ${{ env.FULL_NAME }}"
          echo "Группа: ${{ env.GROUP_NUMBER }}"
          echo "GitHub Nickname: ${{ github.actor }}"

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests

      - name: Line code with flake8
        run: |
          pip install flake8  
          flake8 --ignore=F401 .