name: CI

on:
  push:
    branches:
      - main
      - develop
      - feat/tests
      - release/*
  pull_request:
    branches:
      - main
      - develop
      - feat/tests
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FULL_NAME: "Курилин Тимофей Ильич"
      GROUP_NUMBER: "М3111"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display user information
        run: |
          echo "ФИО: $FULL_NAME"
          echo "Группа: $GROUP_NUMBER"
          echo "GitHub Ник: BrazenFatJR"

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 calculate.py circle.py square.py triangle.py tests/

      - name: Run tests with pytest
        run: |
          pytest
