name: Python CI

on:
  push:
    branches:
      - main
      - develop
      - feat/tests
      - new_feat
      - new_features_465543
  pull_request:
    branches:
      - main
      - develop
      - feat/tests
      - new_feat
      - new_features_465543

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FIO: "Гладких Иван Андреевич"  
      GROUP: "М3117"    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect tests
        run: pytest --collect-only

      - name: Run tests
        run: pytest tests/ --maxfail=1 --disable-warnings -q

      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 .
