name: Python CI
on:
  push:
    branches:
      - main
      - release 
  pull_request:
    branches:
      - main
      - release
      - develop

jobs:
  python-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Output personal information
        env:
          FULL_NAME: ${{ secrets.FULL_NAME }}
          GROUP_NUMBER: ${{ secrets.GROUP_NUMBER }}
        run: |
          echo "Full Name: $FULL_NAME"
          echo "Group Number: $GROUP_NUMBER"
          echo "GitHub Username: $GITHUB_ACTOR"

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pytest --maxfail=1 --disable-warnings -q

      - name: Format code with black (optional)
        run: |
          pip install black
          black .
