name: Automated tests

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
  
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Вывод данных
        run: |
          echo "ФИО: Вахтин Павел Евгеньевич"
          echo "Номер группы: M3114"
          echo "Ник на Github: ${{ github.actor }}"
      - name: Установка библиотек
        run: pip install -r requirements.txt
      - name: Запуск тестов
        run: pytest
      - name: Проверка стиля кода
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
