name: CI Workflow

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - master
      - release
      - develop
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print user information 
      run: |
        echo "Full Name: Непипенко Егор Олегович"
        echo "Group: M3114"
        echo "GitHub Ник: ${{ github.actor }}"

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    
    - name: Run tests
      run: |
        pytest

   
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
