name: CI Workflow

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Set environment variables
        run: |
          echo "NAME=Исаенкова Мария Сергеевна" >> $GITHUB_ENV
          echo "GROUP=M3117" >> $GITHUB_ENV
  

      - name: Print information
        run: |
          echo "ФИО: $NAME"
          echo "Группа: $GROUP"
          echo "Ник на GitHub: marioshka"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check
        run: |
          pytests tests

      - name: Check code style
        run: |
          flake8 .
