name: CI

on:
  push:
    branches:
      - feat/tests
      - release/*
  pull_request:
    branches:
      - master
      - release/*
      - develop

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Check code formatting with Black
      run: |
        black . --check --diff

  stage2_buildtest:
    name: Testing
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Name and Group
      run: |
        echo "Full Name: ${{ secrets.FULL_NAME }}"
        echo "Group Number: ${{ secrets.GROUP_NUMBER }}"
        echo "GitHub Username: ${{ github.actor }}"

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest discover -s tests
