name: Test my library

on:
  push:
    branches: [ new_features_465296 ]

jobs:
  test:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - run: python3 -m unittest test_circle.py
