name: Tests and Linting

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SNP: "Панченко Никита Юрьевич"
      GROUP_NUMBER: "M3111"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: tests
      - name: Print Information
        run: |
          echo "ФИО: ${{ env.SNP }}"
          echo "Номер группы: ${{ env._GROUP_NUMBER }}"
          echo "Ник на Github: ${{ github.actor }}"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: python -m unittest discover tests
        if: ${{ failure() }}
        continue-on-error: false
      - name: Check code style
        run: black --check .
      - name: Format Code (optional)
        run: black .
        if: ${{ failure() }}