name: Tests Workflow

on:
  push:
    branches:
      - feat/tests
      - release/*
  pull_request:
    branches:
      - master
      - release/*
      - develop

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    
    env:
      FULL_NAME: "Lukashenko Kirill Denisovich"
      GROUP_NUMBER: "M3117"
      GITHUB_USERNAME: ${{ github.actor }}

    steps:
    - name: Print Name and Group
      run: |
        echo "Full Name: ${{ env.FULL_NAME }}"
        echo "Group Number: ${{ env.GROUP_NUMBER }}"
        echo "GitHub Username: ${{ env.GITHUB_USERNAME }}"
        
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  

    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Check code formatting with Black
      run: |
        black . --check --diff

  stage2_buildtest:
    name: Testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.13
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest discover -s unit_tests
